//var hostvalue = '//192.168.20.42:7766',
var hostvalue = '//127.0.0.1:5000',
  url = {
    host: hostvalue,
    socketUrl: "localhost:5000/ws",
    getWeSession: "http:" + hostvalue + "/user/getWechatSession",
    sendSmsCode: "http:" + hostvalue + "/auth/sendSmsCode",
    register: "http:" + hostvalue + "/auth/register",
    findPwdAuthSmsCode: "http:" + hostvalue + "/findPwd/authSmsCode",
    findPwdResetPwd: "http:" + hostvalue + "/findPwd/resetPwd",
    login: "http:" + hostvalue + "/auth/login",
    getMainData: "http:" + hostvalue + "/main/getMainData",
    getMineData: "http:" + hostvalue + "/user/getMineData",
    getUserInfo: "http:" + hostvalue + "/user/getUserInfo",
    updateUserInfo: "http:" + hostvalue + "/user/updateUserInfo",
    getResidentList: "http:" + hostvalue + "/user/getResidentList",
    addResident: "http:" + hostvalue + "/user/addResident",
    residentMgr: "http:" + hostvalue + "/user/residentMgr",
    isCanGetBag: "http:" + hostvalue + "/garbagebag/isCanGetBag",
    getGarbageBag: "http:" + hostvalue + "/garbagebag/getGarbageBag",
    getBagHistory: "http:" + hostvalue + "/garbagebag/getBagHistory",
    getRecycleQRCodeInfo: "http:" + hostvalue + "/recycle/getRecycleQRCodeInfo",
    getRecycleHistory: "http:" + hostvalue + "/recycle/getRecycleHistory",
    getTradeQRCodeInfo: "http:" + hostvalue + "/score/getTradeQRCodeInfo",
    getScoreHistory: "http:" + hostvalue + "/score/getScoreHistory",
    updateMobileCheckPwd: "http:" + hostvalue + "/user/settings/updateMobileCheckPwd",
    updateMobileNo: "http:" + hostvalue + "/user/settings/updateMobileNo",
    updatePwd: "http:" + hostvalue + "/user/settings/updatePwd",
    householdAuth: "http:" + hostvalue + "/user/householdAuth",
    getQuestions: "http:" + hostvalue + "/qa/getQuestions",
    submitAnswer: "http:" + hostvalue + "/qa/submitAnswer",
  };
module.exports = url;